/**********************************************************************************************************************
 * \file Ucb_Swap.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <stdlib.h>
#include "IfxFlash.h"
#include "IfxDmu_reg.h"
#include "Ucb_Swap.h"
#include "IfxCpu.h"
#include "ucb_flash.h"

#define UCB_SWAP_ORIG_ADDRESS                   0xAF402E00U
#define UCB_SWAP_ORIG_MARKER_OFFSET             0x00U
#define UCB_SWAP_ORIG_MARKER_REG(x)             (UCB_SWAP_ORIG_ADDRESS + UCB_SWAP_ORIG_MARKER_OFFSET + ((x) * 0x10U))
#define UCB_SWAP_ORIG_CONFIRMATION_OFFSET       0x08U
#define UCB_SWAP_ORIG_CONFIRMATION_REG(x)       (UCB_SWAP_ORIG_ADDRESS + UCB_SWAP_ORIG_CONFIRMATION_OFFSET + ((x) * 0x10U))
#define STANDARD_ADDRESS_MODE                   0x00000055U
#define ALTERNATE_ADDRESS_MODE                  0x000000AAU
#define CONFIRMATION_CODE                       0x57B5327FU

#define UCB_OTP0_ORIG_ADDRESS                   0xAF404000U
#define PROCONTP_OFFSET                         0x1E8U
#define UCB_OTP0_PROCONTP_ADDRESS               (UCB_OTP0_ORIG_ADDRESS + PROCONTP_OFFSET)

typedef struct
{
    EUM_UcbConfirmationType          enConfState;       /**< confirmation state of the UCB block */
    uint32                           u32SwapIndex;      /**< current valid swap marker and confirmation index */
    uint32                           u32SwapValue;      /**< value at swapBase(swapIndex), shall be either 0x55 or 0xAA */
    uint32                           u32NextIndex;      /**< next valid (erased) Index, where a write is allowed to */
    uint8                            u8ValidEntryCnt;   /**< any value bigger than 1 indicate an unfinished log entry sequence */
} ST_SwapUcbInfoType;

typedef struct
{
    uint32                          u32BootSwapValue;  /**< SCU.SWAPCTRL:ADDRCFG based swap value */
    EUM_UcbIndexType                enBootUcbBlock;    /**< SWAP_* UCB confirmation based block, which shall hold bootSwapValue in one entry */
    ST_SwapUcbInfoType              stSwapOrig;        /**< SWAP_ORIG info structure */
    ST_SwapUcbInfoType              stSwapCopy;        /**< SWAP_COPY info structure */
    uint8                           u8BlockUpdReq;     /**< Indicates that dual password sequence must be applied */
} ST_SwapSettingsType;

int test_and_set_STOA(void)
{
    if ((DMU_HF_PROCONTP.U & DMU_HF_PROCONTP_SWAPEN_MASK) != DMU_HF_PROCONTP_SWAPEN) {
        /* enable SOTA */
        write_dflash(UCB_SWAP_ORIG_MARKER_REG(0), STANDARD_ADDRESS_MODE, UCB_SWAP_ORIG_MARKER_REG(0));
        write_dflash(UCB_SWAP_ORIG_CONFIRMATION_REG(0), CONFIRMATION_CODE, UCB_SWAP_ORIG_CONFIRMATION_REG(0));
        write_dflash(UCB_OTP0_PROCONTP_ADDRESS, DMU_HF_PROCONTP_SWAPEN_MASK, 0);

        return 1;
    }
    return 0;
}

static int get_ucb_swap_block_entry(EUM_UcbIndexType enUcbIdx, uint32 u32Index, uint32* pu32SwapValue)
{
    int ret;
    uint32 markerL, markerH;
    uint32 confirmationL, confirmationH;
    uint32 read_buffer[(UCB_SWAP_ENTRY_LENGTH >> 2u)];

    /* Read current UCB swap entry - Any entry causing read error will be ignored */
    ret = ucb_read(enUcbIdx, (u32Index * UCB_SWAP_ENTRY_LENGTH), UCB_SWAP_ENTRY_LENGTH, (uint8 *)read_buffer);

    if (ret == FLASH_ERR_OK) {
        ret = FLASH_ERR_N_OK;

        markerL = read_buffer[(UCB_SWAP_MARKERL_OFFSET >> 2u)];
        markerH = read_buffer[(UCB_SWAP_MARKERH_OFFSET >> 2u)];
        confirmationL = read_buffer[(UCB_SWAP_CONFIRMATIONL_OFFSET >> 2u)];
        confirmationH = read_buffer[(UCB_SWAP_CONFIRMATIONH_OFFSET >> 2u)];

       /* Check entry validity */
       if ((confirmationH == (UCB_ADDRESS(enUcbIdx) + (u32Index * UCB_SWAP_ENTRY_LENGTH) + UCB_SWAP_CONFIRMATIONL_OFFSET)) &&
         (confirmationL == UCB_CONFIRMATION_CONFIRMED_U32) &&
         (markerH == (UCB_ADDRESS(enUcbIdx) + (u32Index * UCB_SWAP_ENTRY_LENGTH) + UCB_SWAP_MARKERL_OFFSET)) && /*  PRQA S 2985  2 */
         ((markerL == 0x55uL) || (markerL == 0xAAuL))) {
           *pu32SwapValue = markerL;
           ret = FLASH_ERR_OK;
       }

    }

    return ret;
}

static void get_ucb_swap_block_info(EUM_UcbIndexType enUcbIdx, ST_SwapUcbInfoType* const pstBlockInfo)
{
    uint8 idx;
    int ret;

    /* Initialize some entries */
    pstBlockInfo->u8ValidEntryCnt  = 0x00u;
    pstBlockInfo->u32SwapIndex     = 0xFFFFFFFFuL;
    pstBlockInfo->u32NextIndex     = 0xFFFFFFFFuL;
    pstBlockInfo->u32SwapValue     = 0x00u;

    for (idx = 0u; idx < UCB_SWAP_NR_OF_ENTRIES; idx++) {
        ret = get_ucb_swap_block_entry(enUcbIdx, idx, &pstBlockInfo->u32SwapValue);
        if(FLASH_ERR_OK == idx) {
            /* Valid entry found */
            pstBlockInfo->u8ValidEntryCnt++;             /* Count valid entries to find possible errors */
            pstBlockInfo->u32SwapIndex = idx;            /* Remember latest index */
            pstBlockInfo->u32NextIndex = 0xFFFFFFFFuL;   /* Reset u32NextIndex to find the next free index after this */
        }

        if ((ret == FLASH_ERR_ERASED) && (pstBlockInfo->u32NextIndex == 0xFFFFFFFFuL)) {
            /* First empty entry after u32SwapIndex */
            pstBlockInfo->u32NextIndex = idx;
        }
    }
}

int get_swap_state(ST_SwapSettingsType *swapState)
{
    int ret = FLASH_ERR_OK;

    swapState->enBootUcbBlock = UCB_NONE;
    swapState->u32BootSwapValue = 0x00u;
    swapState->u8BlockUpdReq   = FALSE;

    if ((DMU_HF_PROCONTP.U & DMU_HF_PROCONTP_SWAPEN_MASK) != DMU_HF_PROCONTP_SWAPEN) {
        ret = FLASH_ERR_N_OK;
    }

    switch (SCU_SWAPCTRL.B.ADDRCFG) {
        case 0x01:
            swapState->u32BootSwapValue = STANDARD_ADDRESS_MODE;
            break;
        case 0x02:
            swapState->u32BootSwapValue = ALTERNATE_ADDRESS_MODE;
            break;
        default:
            ret = FLASH_ERR_N_OK;
          break;
    }

    if (0 == ret) {
        swapState->stSwapOrig.enConfState = ucb_read_confirmation(UCB23_SWAP_ORIG);
        swapState->stSwapCopy.enConfState = ucb_read_confirmation(UCB31_SWAP_COPY);

        /* Check which UCB block holds the latest valid information (is chosen by TC3xx boot sequence )*/
        if((swapState->stSwapOrig.enConfState == UCB_CONFIRMATION_CONFIRMED)
          || (swapState->stSwapOrig.enConfState == UCB_CONFIRMATION_UNLOCKED)) {
            swapState->enBootUcbBlock = UCB23_SWAP_ORIG;

            if (swapState->stSwapOrig.enConfState != swapState->stSwapCopy.enConfState) {
              /* If SWAP_COPY is not a copy of SWAP_ORIG the dual password sequence was interrupted and needs to be restarted. Treat COPY as ERRORED */
              swapState->stSwapCopy.enConfState = UCB_CONFIRMATION_ERRORED;
              swapState->u8BlockUpdReq = TRUE;
            }
        }
        else if((swapState->stSwapCopy.enConfState == UCB_CONFIRMATION_CONFIRMED)
          || (swapState->stSwapCopy.enConfState == UCB_CONFIRMATION_UNLOCKED)) {
            /* ORIG is not valid - take boot settings from COPY and treat ORIG as ERRORED */
            swapState->enBootUcbBlock = UCB31_SWAP_COPY;
            swapState->stSwapOrig.enConfState = UCB_CONFIRMATION_ERRORED;
            swapState->u8BlockUpdReq = TRUE;
        } else {
            /* Reaching this state means that both UCB blocks are ERRORED or ERASED. The device cannot boot in this state. Only reason to get here is that the last SWAP
             * caused dual password sequence, which was interrupted (this explain one UCB block state). In the time between power up and now the 2nd UCB block got an ECC
             * issue and became therefore invalid,too.
             */
            swapState->stSwapOrig.enConfState = UCB_CONFIRMATION_ERRORED;
            swapState->stSwapCopy.enConfState = UCB_CONFIRMATION_ERRORED;

            /* We still have the boot swap value here, but the password may got lost */
            ret = FLASH_ERR_N_OK;
        }
      }

    /* Get informations from the log entries contained in UCB blocks */
    if ((FLASH_ERR_OK == ret) && (swapState->stSwapOrig.enConfState != UCB_CONFIRMATION_ERRORED)) {
      get_ucb_swap_block_info(UCB23_SWAP_ORIG, &(swapState->stSwapOrig));
    }

    if ((FLASH_ERR_OK == ret) && (swapState->stSwapCopy.enConfState != UCB_CONFIRMATION_ERRORED)) {
        get_ucb_swap_block_info(UCB31_SWAP_COPY, &(swapState->stSwapCopy));
    }

    return ret;
}

static void invalidate_swap_entry(EUM_UcbIndexType enUcbIdx, uint32 u32ValidIdx)
{
    if (u32ValidIdx> 0u) {
        uint32 i;
        uint32 dummy;
        uint32 writeBuffer[2u];
        uint32 offset;

        for (i = 0u; i < u32ValidIdx; i++) {
            if (FLASH_ERR_OK == get_ucb_swap_block_entry(enUcbIdx, i, &dummy)) {
                /**
                 *  UCB_SWAP entry is invalidated by over-programming all-1 into CONFIRMATIONL(x-1) (over-programming with all-1
                 *  delivers an ECC correct result for UCB and DFLASH)
                 */
                writeBuffer[0u] = 0xFFFFFFFFuL;
                writeBuffer[1u] = 0xFFFFFFFFuL;

                offset = ((i)* UCB_SWAP_ENTRY_LENGTH) + UCB_SWAP_CONFIRMATIONL_OFFSET;
                /* No useful action if writing will fail */
                (void)ucb_write(enUcbIdx, offset, 8u, (uint8 *)writeBuffer);
            }
        }
    }
}

static int set_swap_entry(EUM_UcbIndexType enUcbIdx, uint32 u32entryStartIdx, uint32 u32SwapVal)
{
    int ret = FLASH_ERR_OK;
    uint32 write_buffer[2];
    uint32 offset;
    uint32 index = u32entryStartIdx;

    if((enUcbIdx != UCB23_SWAP_ORIG) && (enUcbIdx != UCB31_SWAP_COPY)) {
        ret = FLASH_ERR_N_OK;
    }

    if(FLASH_ERR_OK == ret) {
        do {
            write_buffer[0u] = u32SwapVal;
            /* Write address of MARKERL */
            offset = (index * UCB_SWAP_ENTRY_LENGTH) + UCB_SWAP_MARKERL_OFFSET;  /* MD_FBL_2985_RedundantOperation */ /*  PRQA S 2985  2 */
            write_buffer[1u] = UCB_ADDRESS(enUcbIdx) + offset; /*  PRQA S 3469  2 */
            ret = ucb_write(enUcbIdx, offset, 8u, (uint8 *)write_buffer);

            if (FLASH_ERR_OK == ret) {
                write_buffer[0u] = UCB_CONFIRMATION_CONFIRMED_U32;
                /* Write Address of CONFIRMATIONL here */
                offset = (index * UCB_SWAP_ENTRY_LENGTH) + UCB_SWAP_CONFIRMATIONL_OFFSET;
                write_buffer[1u] = UCB_ADDRESS(enUcbIdx) + offset; /*  PRQA S 3469  2 */
                ret = ucb_write(enUcbIdx, offset, 8u, (uint8 *)write_buffer);
            }

            if (FLASH_ERR_OK != ret) {
                index++;
            }
        }
        while ((ret != FLASH_ERR_OK) && (index < UCB_SWAP_NR_OF_ENTRIES));
    }

    invalidate_swap_entry(enUcbIdx, index);

    return ret;
}

static int swap_dual_passwort_sequence(uint32 u32NewSwapValue, EUM_UcbIndexType enReferenceUcb, ST_SwapSettingsType* const swapState)
{
    int ret = FLASH_ERR_OK;
//    uint32 password_backup[8];
    EUM_UcbIndexType en_local_ref_block; /**< Used for changing state */
    uint32 swap_value;

    en_local_ref_block = enReferenceUcb;
    if (en_local_ref_block == UCB23_SWAP_ORIG) {
       /* Full dual password sequence starts here */
        ucb_erase(UCB31_SWAP_COPY);

       /* 1. Copy password */
//        ret = ucb_read(UCB23_SWAP_ORIG, UCB_BLOCK_PW_OFFSET(0u), 32u, (uint8*)password_backup); /*  PRQA S 3469  2 */
//       /* In case of retVal == FLASH_ERR_ERASED: password_backup will be initialized with 0x00 by UcbRead */
//       if ((ret == FLASH_ERR_OK) || (ret == FLASH_ERR_ERASED)) {
//           ret = ucb_write(UCB31_SWAP_COPY, UCB_BLOCK_PW_OFFSET(0u), 32u, (uint8*)password_backup); /*  PRQA S 3469  2 */
//       }

       /* 2. Set new SwapValue */
       if (ret == FLASH_ERR_OK) {
           ret = set_swap_entry(UCB31_SWAP_COPY, 0u, u32NewSwapValue);
       }

       /* 3. Write Confirmation */
       if (ret == FLASH_ERR_OK) {
           ret = ucb_write_confirmation(UCB31_SWAP_COPY, swapState->stSwapOrig.enConfState);
       }

       /* 4. Proceed with 2nd part of the sequence */
       if (ret == FLASH_ERR_OK)
       {
           en_local_ref_block = UCB31_SWAP_COPY;
          /* Update swapSate */
          get_ucb_swap_block_info(UCB31_SWAP_COPY, &(swapState->stSwapCopy));
          swapState->stSwapCopy.enConfState = swapState->stSwapOrig.enConfState;
       }
    }

    if ((ret == FLASH_ERR_OK) && (en_local_ref_block == UCB31_SWAP_COPY)) {
       /* Continue (possibly interrupted) sequence. Rely on the set value if possible. */

       /* 0. Set u32SwapValue relevant for this action */
       if (swapState->stSwapCopy.u8ValidEntryCnt > 0u) {
           swap_value = swapState->stSwapCopy.u32SwapValue;
       } else {
           swap_value = u32NewSwapValue;
       }

       ucb_erase(UCB23_SWAP_ORIG);

       /* 1. Copy password */
//       if (ret == FLASH_ERR_OK) {
//           ret = ucb_read(UCB31_SWAP_COPY, UCB_BLOCK_PW_OFFSET(0u), 32u, (uint8*)password_backup); /*  PRQA S 3469  2 */
//       }
//       /* In case of retVal == FLASH_ERR_ERASED: au32passwordBackup will be initialized with 0x00 by UcbRead */
//       if ((ret == FLASH_ERR_OK) || (ret == FLASH_ERR_ERASED)) {
//           ret = ucb_write(UCB23_SWAP_ORIG, UCB_BLOCK_PW_OFFSET(0u), 32u, (uint8*)password_backup); /*  PRQA S 3469  2 */
//       }

       /* 2. Set new SwapValue */
       if (ret == FLASH_ERR_OK) {
           ret = set_swap_entry(UCB23_SWAP_ORIG, 0u, swap_value);
       }

       /* 3. Write Confirmation */
       if (ret == FLASH_ERR_OK) {
          /* Result will be set outside by reading back and check any value */
          (void)ucb_write_confirmation(UCB23_SWAP_ORIG, swapState->stSwapCopy.enConfState);
       }
    }

    return ret;
}

int swap_bank(void)
{
    ST_SwapSettingsType ucb_swap_state = {0};
    uint32 retry_fail_cnt = 0;
    uint32 new_swap_value = 0x00000000uL;
    int ret = FLASH_ERR_OK;

    while (FLASH_ERR_OK == ret) {
        ret = get_swap_state(&ucb_swap_state);
        if (FLASH_ERR_OK == ret) {
           /* SWAP support is enabled, we have boot swap value and at least one valid UCB block */
            new_swap_value = ucb_swap_state.u32BootSwapValue ^ 0xFFuL;
        }

        if ((FLASH_ERR_OK == ret) && (ucb_swap_state.u8BlockUpdReq == FALSE)) {
            /* Both UCB blocks are valid, no reason found to repair a UCB block. stUcbSwapState.bootUcbBlock = ORIG */
            /* Check if the swap request was already correctly set and logs of both UCB blocks are valid */
            if ((ucb_swap_state.stSwapOrig.u32SwapIndex < UCB_SWAP_NR_OF_ENTRIES) && /* Valid entry available - u32SwapValue can be evaluated */
                (ucb_swap_state.stSwapCopy.u32SwapIndex < UCB_SWAP_NR_OF_ENTRIES) && /* Both UCB blocks need valid log entries */
                (ucb_swap_state.stSwapOrig.u32SwapValue == new_swap_value) &&                /* Both valid UCB log entries need to have same expected value */
                (ucb_swap_state.stSwapCopy.u32SwapValue == new_swap_value) &&
                (ucb_swap_state.stSwapOrig.u8ValidEntryCnt == 1u) &&                      /* Log in UCB is only valid if there is just one valid entry */
                (ucb_swap_state.stSwapCopy.u8ValidEntryCnt == 1u)) {
               /* Valid blocks and entries found with new swap value. System Reset required no further actions */
               /*******************************************************************/
               break; /* One and only place to leave the loop with a valid result */
               /*******************************************************************/
            }

            /* Check if any UCB block needs to be updated by dual password sequence */
            if (((ucb_swap_state.stSwapOrig.u32NextIndex >= UCB_SWAP_NR_OF_ENTRIES) && (ucb_swap_state.stSwapOrig.u32SwapValue != new_swap_value)) ||
                ((ucb_swap_state.stSwapCopy.u32NextIndex >= UCB_SWAP_NR_OF_ENTRIES) && (ucb_swap_state.stSwapCopy.u32SwapValue != new_swap_value))) {
                /* There is at least one UCB block, which has not already the correct swap value and no remaining log entry to write new value */
                ucb_swap_state.u8BlockUpdReq = TRUE; /* Force dual password sequence. */
            }

            /* Remove old but still valid entries for UCB blocks - Results will be seen in next loop */
            if ((ucb_swap_state.u8BlockUpdReq == FALSE) && (ucb_swap_state.stSwapOrig.u8ValidEntryCnt > 1u)) {
                invalidate_swap_entry(UCB23_SWAP_ORIG, ucb_swap_state.stSwapOrig.u32SwapIndex);
            }
            if ((ucb_swap_state.u8BlockUpdReq == FALSE) && (ucb_swap_state.stSwapCopy.u8ValidEntryCnt > 1u)) {
                invalidate_swap_entry(UCB31_SWAP_COPY, ucb_swap_state.stSwapCopy.u32SwapIndex);
            }

            /* Write new values if not already set - Results will be seen in next loop */
            /* First set value in COPY and then in ORIG, analogous to dual password sequence:
             * So when we boot next time after any interruption from new value, we can be sure that
             * this value is present in COPY, too
             */
            if ((ucb_swap_state.u8BlockUpdReq == FALSE) && (ucb_swap_state.stSwapCopy.u32SwapValue != new_swap_value)) {
               if (FLASH_ERR_OK != set_swap_entry(UCB31_SWAP_COPY, ucb_swap_state.stSwapCopy.u32NextIndex, new_swap_value)) {
                  continue; /* Re evaluate state in next loop cycle */
               }
            }
            if ((ucb_swap_state.u8BlockUpdReq == FALSE) && (ucb_swap_state.stSwapOrig.u32SwapValue != new_swap_value)) {
              /* Result will be automatically updated by next loop cycle */
              (void)set_swap_entry(UCB23_SWAP_ORIG, ucb_swap_state.stSwapOrig.u32NextIndex, new_swap_value);
            }
        }

        if ((FLASH_ERR_OK == ret) && (ucb_swap_state.u8BlockUpdReq == TRUE)) {
           /* Dual password sequence must be executed. Result of this operation will be evaluated in next loop by reading written data. */
           if (swap_dual_passwort_sequence(new_swap_value, ucb_swap_state.enBootUcbBlock, &ucb_swap_state) != FLASH_ERR_OK) {
               retry_fail_cnt++;
           } else {
               retry_fail_cnt = 0;
           }
        }

        if (retry_fail_cnt >= SWAP_RETRY_CNT) {
           /* Maximum number of retries achived. The device has an hardware failure */
           ret = FLASH_ERR_N_OK;
        }
    }

    return ret;
}

