/**********************************************************************************************************************
 * \file ucb_flash.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <string.h>
#include "IfxFlash.h"
#include "IfxCpu.h"
#include "IfxDmu_reg.h"
#include "IfxScu_reg.h"
#include "ucb_flash.h"
#include "Bsp.h"

#define FLASH_MODULE                0                           /* Macro to select the flash (PMU) module           */
#define DATA_FLASH_0                IfxFlash_FlashType_D0       /* Define the Data Flash Bank to be used            */

const uint32 s_au32UcbUnlockedPattern[UCB_CONFIRMATION_WRITE_LENGTH_IN_WORD] = {UCB_CONFIRMATION_UNLOCKED_U32, 0x00000000u, 0x00000000u, 0x00000000u};
const uint32 s_au32UcbConfirmedPattern[UCB_CONFIRMATION_WRITE_LENGTH_IN_WORD] = {UCB_CONFIRMATION_CONFIRMED_U32, 0x00000000u, 0x00000000u, 0x00000000u};

/* The following arrays describe the known set of TC3xx swap able flash configurations */
const ST_SwapOffsetCfgType astFlashSwapCfg_7of16Mb[] =
{
   { 0xA0000000uL, 0xA05FFFFFuL, 0x00600000uL },
   { 0xA0600000uL, 0xA0BFFFFFuL, 0xFFA00000uL }, /* -0x00600000 */
   { 0xA0C00000uL, 0xA0CFFFFFuL, 0x00300000uL },
   { 0xA0F00000uL, 0xA0FFFFFFuL, 0xFFD00000uL }  /* -0x00300000 */
};

const ST_SwapOffsetCfgType astFSwapCfg_4of10Mb[] =
{
   { 0xA0000000uL, 0xA03FFFFFuL, 0x00600000uL },
   { 0xA0600000uL, 0xA09FFFFFuL, 0xFFA00000uL }  /* -0x00600000 */
};

const ST_SwapOffsetCfgType astFlashSwapCfg_4of8Mb[] =
{
   { 0xA0000000uL, 0xA03FFFFFuL, 0x00600000uL },
   { 0xA0600000uL, 0xA09FFFFFuL, 0xFFA00000uL }  /* -0x00600000 */
};

const ST_SwapOffsetCfgType astFlashSwapCfg_3of6Mb[] =
{
   { 0xA0000000uL, 0xA02FFFFFuL, 0x00300000uL },
   { 0xA0300000uL, 0xA05FFFFFuL, 0xFFD00000uL }  /* -0x00300000 */
};

const ST_SwapOffsetCfgType astFlashSwapCfg_2of4Mb[] =
{
   { 0xA0000000uL, 0xA01FFFFFuL, 0x00300000uL },
   { 0xA0300000uL, 0xA04FFFFFuL, 0xFFD00000uL }  /* -0x00300000 */
};

const ST_SwapDeviceCfgType stFlashSwap16MBCfg = {(sizeof(astFlashSwapCfg_7of16Mb)/sizeof(astFlashSwapCfg_7of16Mb[0u])), astFlashSwapCfg_7of16Mb};
const ST_SwapDeviceCfgType stFlashSwap10MBCfg = {(sizeof(astFSwapCfg_4of10Mb)/sizeof(astFSwapCfg_4of10Mb[0u])), astFSwapCfg_4of10Mb};
const ST_SwapDeviceCfgType stFlashSwap8MBCfg  = {(sizeof(astFlashSwapCfg_4of8Mb)/sizeof(astFlashSwapCfg_4of8Mb[0u])), astFlashSwapCfg_4of8Mb};
const ST_SwapDeviceCfgType stFlashSwap6MBCfg  = {(sizeof(astFlashSwapCfg_3of6Mb)/sizeof(astFlashSwapCfg_3of6Mb[0u])), astFlashSwapCfg_3of6Mb};
const ST_SwapDeviceCfgType stFlashSwap4MBCfg  = {(sizeof(astFlashSwapCfg_2of4Mb)/sizeof(astFlashSwapCfg_2of4Mb[0u])), astFlashSwapCfg_2of4Mb};

/* Based on CHIPID value */
const ST_SwapDevLookUpTblType flashDevLookUpTbl[] =
{
   {0x0F00F0C0uL, 0x0F009080uL, &stFlashSwap16MBCfg},   /* FSIZE = 0xF = 16MB, CHID = 0x9 = TC39xx, CHTEC = 0x2 = SAx-TC3xx */
   {0x0F00F0C0uL, 0x0C008080uL, &stFlashSwap10MBCfg},   /* FSIZE = 0xC = 10MB, CHID = 0x8 = TC38xx, CHTEC = 0x2 = SAx-TC3xx */
   {0x0F00F0C0uL, 0x0B008080uL, &stFlashSwap8MBCfg},    /* FSIZE = 0xB =  8MB, CHID = 0x8 = TC38xx, CHTEC = 0x2 = SAx-TC3xx */
   {0x0F00F0C0uL, 0x09007080uL, &stFlashSwap6MBCfg},    /* FSIZE = 0x9 =  6MB, CHID = 0x7 = TC37xx, CHTEC = 0x2 = SAx-TC3xx */
   {0x0F00F0C0uL, 0x07006080uL, &stFlashSwap4MBCfg},    /* FSIZE = 0x7 =  4MB, CHID = 0x6 = TC36xx, CHTEC = 0x2 = SAx-TC3xx */
   {0x0F00F0C0uL, 0x07005080uL, &stFlashSwap4MBCfg},    /* FSIZE = 0x7 =  4MB, CHID = 0x5 = TC35xx, CHTEC = 0x2 = SAx-TC3xx */
};

static int verify_erased_page(uint32 verifyAddress)
{
    int ret;
    boolean interruptState = IfxCpu_disableInterrupts(); /* Get the current state of the interrupts and disable them*/

    DMU_HF_CLRE.U = HF_CLER_MASK_CSQER | HF_CLER_MASK_CPROER | HF_CLER_MASK_CEVER;

    __dsync();
    volatile uint32 *addr1 = (volatile uint32 *)(IFXFLASH_CMD_BASE_ADDRESS | 0x5554);
    *addr1 = 0xf0;
    __dsync();

    IfxFlash_verifyErasedPage(verifyAddress);

    /* If it is in  busy state, polling waits. */
    while((DMU_HF_STATUS.U & FLASH_STATUS_MASK_BUSY) != 0u) {}

    if((DMU_HF_ERRSR.U & HF_ERRSR_MASK_SQER) == HF_ERRSR_MASK_SQER) {
        ret = FLASH_ERR_N_OK;
    } else if((DMU_HF_ERRSR.U & HF_ERRSR_MASK_EVER) == HF_ERRSR_MASK_EVER) {
        ret = FLASH_ERR_OK;
    } else if((DMU_HF_ERRSR.U & HF_ERRSR_MASK_PROER) == HF_ERRSR_MASK_PROER) {
        ret = FLASH_ERR_OK;
    } else {
        ret = FLASH_ERR_ERASED;
    }

    IfxCpu_restoreInterrupts(interruptState);            /* Restore the interrupts state */

    return ret;
}

int verify_erased_range(uint32 verifyAddress, uint32 verifyLength)
{
    uint32 uncached_addr;
    uint32 verifyd_address;
    uint32 aligned_address;
    uint32 aligned_end_address;
    uint32 flash_page_size;
    int ret;

    uncached_addr = verifyAddress | PFLASH_UNCACHED_BASE_ADDRESS;
    if((uncached_addr & DFLASH_BASE_ADDRESS) == DFLASH_BASE_ADDRESS) {
        /* Verify Dflash. */
        flash_page_size     = FLASH_DFLASH_PAGE_SIZE;
    } else {
        /* Verify Pflash. */
        flash_page_size     = FLASH_PFLASH_PAGE_SIZE;
    }

    aligned_address  = uncached_addr & ((uint32)(flash_page_size - 1u)^0xFFFFFFFFu);
    aligned_end_address = (uncached_addr + verifyLength + flash_page_size - 1u) & ((uint32)(flash_page_size - 1u)^0xFFFFFFFFu);

    ret = verify_erased_page(aligned_address);
    if(ret == FLASH_ERR_OK) {
        for(verifyd_address = aligned_address + flash_page_size; verifyd_address < aligned_end_address; verifyd_address += flash_page_size) {
            /* Check the status of the remaining Page. */
            ret = verify_erased_page(verifyd_address);
            if(FLASH_ERR_OK != ret) {
                break;
            }
        }
    }

    return ret;
}

int get_swap_offset_cfg(uint32 normalAddress, ST_SwapOffsetCfgType * pstSwapOffsetCfg)
{
    uint8 idx;
    const ST_SwapDeviceCfgType*  ptr_local_swap_dev_cfg = NULL_PTR;
    int ret = 1;

    /* Get device config */
    for(idx = 0; idx < (sizeof(flashDevLookUpTbl)/sizeof(flashDevLookUpTbl[0])); idx++) {
        if((SCU_CHIPID.U & flashDevLookUpTbl[idx].u32DevIdMask) == flashDevLookUpTbl[idx].u32DevIdValue) {
            ptr_local_swap_dev_cfg = (ST_SwapDeviceCfgType *)flashDevLookUpTbl[idx].devCfg;
            break;
        }
    }

    /* Applying offset */
    if(NULL_PTR != ptr_local_swap_dev_cfg) {
        for(idx = 0u; idx < ptr_local_swap_dev_cfg->u32EntryCount; idx++) {
            if((normalAddress >= ptr_local_swap_dev_cfg->pstCfgEntry[idx].u32SwapAreaStartAddr)
                    && (normalAddress <= ptr_local_swap_dev_cfg->pstCfgEntry[idx].u32SwapAreaEndAddr)){
                *pstSwapOffsetCfg = ptr_local_swap_dev_cfg->pstCfgEntry[idx];
                ret = 0;
                break;
            }
        }
    }

    return ret;
}

static void get_swap_addr(uint32 *pAddr)
{
    uint32 normal_address;
    uint32 swapped_address;
    ST_SwapOffsetCfgType swap_offset_cfg;
    int ret = 1;

    normal_address = *pAddr;

    ret = get_swap_offset_cfg(normal_address, &swap_offset_cfg);
    if((0 == ret) && ((DMU_HF_PROCONTP.U & DMU_HF_PROCONTP_SWAPEN_MASK) == DMU_HF_PROCONTP_SWAPEN)) {
        if(SCU_SWAPCTRL_ADDRCFG_ALT == (SCU_SWAPCTRL.U & SCU_SWAPCTRL_ADDRCFG_MASK)) {
            swapped_address = normal_address + swap_offset_cfg.u32SwapAreaOffset;
            *pAddr = swapped_address;
        }
    }

}

int flash_read(uint32 readStartAddr, uint32 readLength, uint8 *pu8ReadBuffer)
{
    int ret = 0;
    uint32 uncached_addr;

    uncached_addr = readStartAddr | PFLASH_UNCACHED_BASE_ADDRESS;

    ret = verify_erased_range(uncached_addr, readLength);

    get_swap_addr(&uncached_addr);

    if(FLASH_ERR_ERASED == ret) {
        /* If the region read is in the erased state, the values read are all 0xFF. */
        (void)memset((void*)pu8ReadBuffer, 0xFFu, readLength);   /*  PRQA S 3335 */
    } else if(FLASH_ERR_OK == ret) {
        /* If the data in the read area is not erased, the data is read to the buffer. */
        (void)memcpy(pu8ReadBuffer, (uint8 *)uncached_addr, readLength);   /*  PRQA S 3335 */
    } else {
        /* Read encounter error. */
    }

    return ret;
}

int ucb_read(EUM_UcbIndexType enUcbIdx, uint32 readOffset, uint32 readLength, uint8 *pu8ReadBuffer)
{
    int ret = FLASH_ERR_OK;
    uint32 read_addr;

    read_addr = UCB_ADDRESS(enUcbIdx) + readOffset;

    if ((read_addr & DFLASH_BASE_ADDRESS) != DFLASH_BASE_ADDRESS) {
        ret = FLASH_ERR_INVALID_ADDR;
    } else if ((read_addr < UCB_ADDRESS(enUcbIdx)) || ((read_addr + readLength) > UCB_ADDRESS(((uint32)(enUcbIdx)) + 1u))) {
        ret = FLASH_ERR_INVALID_PARAM;
    } else {

    }

    if (FLASH_ERR_OK == ret) {
        ret = flash_read(read_addr, readLength, pu8ReadBuffer);
    }

    return ret;
}

EUM_UcbConfirmationType ucb_read_confirmation(EUM_UcbIndexType enUcbIdx)
{
    EUM_UcbConfirmationType ucb_confirm_state;
    uint32 read_buffer[UCB_CONFIRMATION_READ_LENGTH_IN_WORD];
    uint8  is_not_unlocked;
    uint8 idx;
    int ret;
//    uint32 s_au32UcbUnlockedPattern[UCB_CONFIRMATION_WRITE_LENGTH_IN_WORD] = {UCB_CONFIRMATION_UNLOCKED_U32, 0x00000000u, 0x00000000u, 0x00000000u};
//    uint32 s_au32UcbConfirmedPattern[UCB_CONFIRMATION_WRITE_LENGTH_IN_WORD] = {UCB_CONFIRMATION_CONFIRMED_U32, 0x00000000u, 0x00000000u, 0x00000000u};

    ret = ucb_read(enUcbIdx, UCB_CONFIRMATION_OFFSET, UCB_CONFIRMATION_READ_LENGTH_IN_BYTE, (uint8 *)read_buffer);
    if(FLASH_ERR_OK == ret) {
        ucb_confirm_state = UCB_CONFIRMATION_UNLOCKED;
        is_not_unlocked   = FALSE;

        for(idx = 0u; idx < UCB_CONFIRMATION_READ_LENGTH_IN_WORD; idx++) {
            if(read_buffer[idx] != s_au32UcbUnlockedPattern[idx]) {
                is_not_unlocked = TRUE;
                break;
            }
        }

        if(TRUE == is_not_unlocked) {
            ucb_confirm_state = UCB_CONFIRMATION_CONFIRMED;

            for(idx = 0u; idx < UCB_CONFIRMATION_READ_LENGTH_IN_WORD; idx++) {
                if(read_buffer[idx] != s_au32UcbConfirmedPattern[idx]) {
                    ucb_confirm_state = UCB_CONFIRMATION_ERRORED;
                    break;
                }
            }
        }
    } else {
        ucb_confirm_state = UCB_CONFIRMATION_ERRORED;
    }

    return ucb_confirm_state;
}

void write_dflash(uint32 addr, uint32 val_l, uint32 val_h)
{
    /* Get the current password of the Safety WatchDog module */
    uint16 endInitSafetyPassword = IfxScuWdt_getSafetyWatchdogPassword();

    /* Enter in page mode */
    IfxFlash_enterPageMode(addr);

    /* Wait until page mode is entered */
    IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);

    /* Load data to be written in the page */
    IfxFlash_loadPage2X32(addr, val_l, val_h);

    /* Write the loaded page */
    IfxScuWdt_clearSafetyEndinit(endInitSafetyPassword);    /* Disable EndInit protection                       */
    IfxFlash_writePage(addr);                               /* Write the page                                   */
    IfxScuWdt_setSafetyEndinit(endInitSafetyPassword);      /* Enable EndInit protection                        */

    /* Wait until the data is written in the Data Flash memory */
    IfxFlash_waitUnbusy(FLASH_MODULE, DATA_FLASH_0);
}

int ucb_write(EUM_UcbIndexType enUcbIdx, uint32 writeOffset, uint32 writeLength, uint8 *WriterBuffer)
{
    uint32  ucb_write_addr;
    uint32 *data;
    uint32 count = 0;
    uint32 remain = 0;
    uint32 i = 0;
    int ret = FLASH_ERR_OK;

    ucb_write_addr = UCB_ADDRESS(enUcbIdx) + writeOffset;
    if((ucb_write_addr & DFLASH_BASE_ADDRESS) != DFLASH_BASE_ADDRESS) {
        ret = FLASH_ERR_INVALID_ADDR;
    } else if((ucb_write_addr < UCB_ADDRESS(enUcbIdx)) || ((ucb_write_addr + writeLength) > UCB_ADDRESS(((uint32)(enUcbIdx)) + 1u))) {
        ret = FLASH_ERR_INVALID_PARAM;
    } else if((ucb_write_addr & (FLASH_DFLASH_PAGE_SIZE - 1u)) != 0u) {
        ret = FLASH_ERR_WRITE_INVALID_ADDR;
    } else if((writeLength & (FLASH_DFLASH_PAGE_SIZE - 1u)) != 0u) {
        ret  = FLASH_ERR_WRITE_INVALID_LEN;
    } else {
        data = (uint32 *)WriterBuffer;
        count = writeLength / FLASH_DFLASH_PAGE_SIZE;
        remain = writeLength % FLASH_DFLASH_PAGE_SIZE;
    }

    if (0 != remain) {
        ret = FLASH_ERR_INVALID_PARAM;
    }

    if(FLASH_ERR_OK == ret) {
        for (i = 0; i < count; i+=2) {
            write_dflash(ucb_write_addr, data[i], data[i+1]);
            ucb_write_addr += FLASH_DFLASH_PAGE_SIZE;
        }
    }

    return FLASH_ERR_OK;
}

void ucb_erase(EUM_UcbIndexType enUcbIdx)
{
    uint32 ucb_addr;

    ucb_addr = UCB_ADDRESS(enUcbIdx);
    IfxFlash_eraseMultipleSectors(ucb_addr, 1);

    /* Wait until the data is erase Flash memory */
    waitTime(100000000);
}

int ucb_write_confirmation(EUM_UcbIndexType enUcbIdx, EUM_UcbConfirmationType enUcbConfirmState)
{
    int ret;

    if (UCB_CONFIRMATION_UNLOCKED == enUcbConfirmState) {
        ret = ucb_write(enUcbIdx, UCB_CONFIRMATION_OFFSET, UCB_CONFIRMATION_WRITE_LENGTH_IN_BYTE, \
                                        (uint8 *)s_au32UcbUnlockedPattern);
    } else if(UCB_CONFIRMATION_CONFIRMED == enUcbConfirmState) {
        ret = ucb_write(enUcbIdx, UCB_CONFIRMATION_OFFSET, UCB_CONFIRMATION_WRITE_LENGTH_IN_BYTE, \
                       (uint8 *)s_au32UcbConfirmedPattern);
    } else {
        ret = FLASH_ERR_N_OK;
    }

    return ret;
}
