#ifndef __TC387_IRQ_PRIORITY_H_
#define __TC387_IRQ_PRIORITY_H_

#include "tc387_def.h"

enum {
    ISR_PRIORITY_NONE = 0,
    /*           DEBUG UART      */
    ISR_PRIORITY_DEBUG_UART_TX,
    ISR_PRIORITY_DEBUG_UART_RX,
    ISR_PRIORITY_DEBUG_UART_ERR,
    /*            UNKNOW         */
    ISR_PRIORITY_SCUERU_INT0,
    /*            MAC INIT       */
    ISR_PRIORITY_SYSTEM_POWER,
    /*            OS TICK       */
    ISR_PRIORITY_OS_TICK,
    /*           CPU LOAD         */
#if (USE_CPU0_LOAD)
    ISR_PRIORITY_CPU0_LOAD,
#endif
#if (USE_CPU1_LOAD)
    ISR_PRIORITY_CPU1_LOAD,
#endif
#if (USE_CPU2_LOAD)
    ISR_PRIORITY_CPU2_LOAD,
#endif
#if (USE_CPU3_LOAD)
    ISR_PRIORITY_CPU3_LOAD,
#endif
    /*           ASCLIN TX       */
    ISR_PRIORITY_ASCLIN0_TX,
    ISR_PRIORITY_ASCLIN1_TX,
    ISR_PRIORITY_ASCLIN2_TX,
    ISR_PRIORITY_ASCLIN3_TX,
    ISR_PRIORITY_ASCLIN4_TX,
    ISR_PRIORITY_ASCLIN5_TX,
    ISR_PRIORITY_ASCLIN6_TX,
    ISR_PRIORITY_ASCLIN7_TX,
    ISR_PRIORITY_ASCLIN8_TX,
    ISR_PRIORITY_ASCLIN9_TX,
    ISR_PRIORITY_ASCLIN10_TX,
    ISR_PRIORITY_ASCLIN11_TX,
    ISR_PRIORITY_ASCLIN13_TX,
    ISR_PRIORITY_ASCLIN14_TX,
    ISR_PRIORITY_ASCLIN15_TX,
    ISR_PRIORITY_ASCLIN16_TX,
    /*           MCAN TX         */
    ISR_PRIORITY_MACN_NODE0_TX,
    ISR_PRIORITY_MACN_NODE1_TX,
    ISR_PRIORITY_MACN_NODE2_TX,
    ISR_PRIORITY_MACN_NODE3_TX,
    ISR_PRIORITY_MACN_NODE4_TX,
    ISR_PRIORITY_MACN_NODE5_TX,
    ISR_PRIORITY_MACN_NODE6_TX,
    ISR_PRIORITY_MACN_NODE7_TX,
    /*           ASCLIN RX       */
    ISR_PRIORITY_ASCLIN0_RX,
    ISR_PRIORITY_ASCLIN1_RX,
    ISR_PRIORITY_ASCLIN2_RX,
    ISR_PRIORITY_ASCLIN3_RX,
    ISR_PRIORITY_ASCLIN4_RX,
    ISR_PRIORITY_ASCLIN5_RX,
    ISR_PRIORITY_ASCLIN6_RX,
    ISR_PRIORITY_ASCLIN7_RX,
    ISR_PRIORITY_ASCLIN8_RX,
    ISR_PRIORITY_ASCLIN9_RX,
    ISR_PRIORITY_ASCLIN10_RX,
    ISR_PRIORITY_ASCLIN11_RX,
    ISR_PRIORITY_ASCLIN13_RX,
    ISR_PRIORITY_ASCLIN14_RX,
    ISR_PRIORITY_ASCLIN15_RX,
    ISR_PRIORITY_ASCLIN16_RX,
    /*           MCAN RX         */
    ISR_PRIORITY_MACN_NODE0_RX,
    ISR_PRIORITY_MACN_NODE1_RX,
    ISR_PRIORITY_MACN_NODE2_RX,
    ISR_PRIORITY_MACN_NODE3_RX,
    ISR_PRIORITY_MACN_NODE4_RX,
    ISR_PRIORITY_MACN_NODE5_RX,
    ISR_PRIORITY_MACN_NODE6_RX,
    ISR_PRIORITY_MACN_NODE7_RX,
    /*           ASCLIN ERR      */
    ISR_PRIORITY_ASCLIN0_ERR,
    ISR_PRIORITY_ASCLIN1_ERR,
    ISR_PRIORITY_ASCLIN2_ERR,
    ISR_PRIORITY_ASCLIN3_ERR,
    ISR_PRIORITY_ASCLIN4_ERR,
    ISR_PRIORITY_ASCLIN5_ERR,
    ISR_PRIORITY_ASCLIN6_ERR,
    ISR_PRIORITY_ASCLIN7_ERR,
    ISR_PRIORITY_ASCLIN8_ERR,
    ISR_PRIORITY_ASCLIN9_ERR,
    ISR_PRIORITY_ASCLIN10_ERR,
    ISR_PRIORITY_ASCLIN11_ERR,
    ISR_PRIORITY_ASCLIN13_ERR,
    ISR_PRIORITY_ASCLIN14_ERR,
    ISR_PRIORITY_ASCLIN15_ERR,
    ISR_PRIORITY_ASCLIN16_ERR,
    /*           ETHNET       */
    ISR_PRIORITY_GETH_TX,
    ISR_PRIORITY_GETH_RX,
    /*           QSPI         */
    ISR_PRIORITY_QSPI_TX,
    ISR_PRIORITY_QSPI_RX,     
    ISR_PRIORITY_QSPI_ERR,
    ISR_PRIORITY_MAX
};

#endif /* __TC387_IRQ_PRIORITY_H_ */
