/**********************************************************************************************************************
 * \file ucb_flash.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef UCB_FLASH_H_
#define UCB_FLASH_H_

#define FLASH_ERR_OK                                 0x00u
#define FLASH_ERR_N_OK                               0x01u
#define FLASH_ERR_OPER                               0x02u
#define FLASH_ERR_SQER                               0x03u
#define FLASH_ERR_PROER                              0x04u
#define FLASH_ERR_PVER                               0x05u
#define FLASH_ERR_EVER                               0x06u
#define PFLASH_ERR_PAGE_MODE                         0x07u
#define FLASH_ERR_LOAD_PAGE                          0x08u
#define FLASH_ERR_INVALID_ADDR                       0x09u
#define FLASH_ERR_INVALID_LEN                        0x0Au
#define FLASH_ERR_BUF_UNALIGNED                      0x0Bu
#define FLASH_ERR_INVALID_PARAM                      0x0Cu
#define FLASH_ERR_ERASED                             0xEAu

#define FLASH_ERR_FUNC_INIT                          0x10u
#define FLASH_ERR_FUNC_ERASE                         0x20u
#define FLASH_ERR_FUNC_WRITE                         0x40u

#define FLASH_ERR_ERASE_INVALID_ADDR                 (FLASH_ERR_FUNC_ERASE | FLASH_ERR_INVALID_ADDR)
#define FLASH_ERR_ERASE_INVALID_LEN                  (FLASH_ERR_FUNC_ERASE | FLASH_ERR_INVALID_LEN)
#define FLASH_ERR_ERASE_INVALID_PARAM                (FLASH_ERR_FUNC_ERASE | FLASH_ERR_INVALID_PARAM)

#define FLASH_ERR_WRITE_INVALID_ADDR                 (FLASH_ERR_FUNC_WRITE | FLASH_ERR_INVALID_ADDR)
#define FLASH_ERR_WRITE_INVALID_LEN                  (FLASH_ERR_FUNC_WRITE | FLASH_ERR_INVALID_LEN)
#define FLASH_ERR_WRITE_BUF_UNALIGNED                (FLASH_ERR_FUNC_WRITE | FLASH_ERR_BUF_UNALIGNED)
#define FLASH_ERR_WRITE_INVALID_PARAM                (FLASH_ERR_FUNC_WRITE | FLASH_ERR_INVALID_PARAM)

#define DFLASH_BASE_ADDRESS                          0xAF000000u    /**< Dflash base sddress. */
#define PFLASH_UNCACHED_BASE_ADDRESS                 0xA0000000u    /**< PFlash uncached base address */
#define FLASH_DFLASH_PAGE_SIZE                       0x00000008u
#define FLASH_PFLASH_PAGE_SIZE                       0x00000020u
#define FLASH_DFLASH_BURST_SIZE                      (FLASH_DFLASH_PAGE_SIZE * 4u)
#define FLASH_PFLASH_BURST_SIZE                      (FLASH_PFLASH_PAGE_SIZE * 8u)

#define UCB_BASE_ADDR                                0xAF400000u    /**< UCB base address */
#define UCB_LOGICAL_SECTOR_SIZE                      0x200          /**< DFLASH0 UCB Logical Sector size. */
#define UCB_ADDRESS(UcbIdx)                          (UCB_BASE_ADDR + UCB_LOGICAL_SECTOR_SIZE * ((uint32)(UcbIdx)))

#define UCB_BLOCK_PW_OFFSET(i)                       (0x100u + ((i) * 4u)) /**< Offset of PWi in UCB Block */

#define UCB_CONFIRMATION_OFFSET                      0x01F0u
#define UCB_CONFIRMATION_READ_LENGTH_IN_BYTE         0x0004u
#define UCB_CONFIRMATION_READ_LENGTH_IN_WORD         0x0001u

#define HF_CLER_MASK_CSQER                           0x00000002u    /**< Clear Error Register: Clear Command Sequence Error. */
#define HF_CLER_MASK_CPROER                          0x00000004u    /**< Clear Error Register: Clear Protection Error. */
#define HF_CLER_MASK_CEVER                           0x00000010u    /**< Clear Error Register: Clear Erase Verify Error. */

#define HF_STATUS_MASK_D0BUSY                        0x00000001u    /**< Flash Status Register: Data Flash Bank 0 Busy. */
#define HF_STATUS_MASK_D1BUSY                        0x00000002u    /**< Flash Status Register: Data Flash Bank 1 Busy. */
#define HF_STATUS_MASK_P0BUSY                        0x00000004u    /**< Flash Status Register: Program Flash PF0BUSY. */
#define HF_STATUS_MASK_P1BUSY                        0x00000008u    /**< Flash Status Register: Program Flash PF0BUSY. */
#define HF_STATUS_MASK_P2BUSY                        0x00000010u    /**< Flash Status Register: Program Flash PF1BUSY. */
#define HF_STATUS_MASK_P3BUSY                        0x00000020u    /**< Flash Status Register: Program Flash PF2BUSY. */
#define HF_STATUS_MASK_P4BUSY                        0x00000040u    /**< Flash Status Register: Program Flash PF3BUSY. */
#define HF_STATUS_MASK_P5BUSY                        0x00000080u    /**< Flash Status Register: Program Flash PF5BUSY. */
#define FLASH_STATUS_MASK_BUSY                       (HF_STATUS_MASK_D0BUSY | HF_STATUS_MASK_D1BUSY | HF_STATUS_MASK_P0BUSY | HF_STATUS_MASK_P1BUSY | HF_STATUS_MASK_P2BUSY | HF_STATUS_MASK_P3BUSY | HF_STATUS_MASK_P4BUSY | HF_STATUS_MASK_P5BUSY)

#define HF_ERRSR_MASK_OPER                           0x00000001u    /**< Error Status Register: Flash Operation Error.*/
#define HF_ERRSR_MASK_SQER                           0x00000002u    /**< Error Status Register: Command Sequence Error.*/
#define HF_ERRSR_MASK_PROER                          0x00000004u    /**< Error Status Register: Protection Error.*/
#define HF_ERRSR_MASK_PVER                           0x00000008u    /**< Error Status Register: Program Verify Error.*/
#define HF_ERRSR_MASK_EVER                           0x00000010u    /**< Error Status Register: Erase Verify Error.*/
#define FLASH_STATUS_MASK_ERR                        (HF_ERRSR_MASK_OPER | HF_ERRSR_MASK_SQER | HF_ERRSR_MASK_PROER | HF_ERRSR_MASK_PVER | HF_ERRSR_MASK_EVER )

#define DMU_HF_PROCONTP_SWAPEN                       0x00030000U
#define DMU_HF_PROCONTP_SWAPEN_MASK                  0x00030000U
#define SCU_SWAPCTRL_ADDRCFG_MASK                    0x00000003u
#define SCU_SWAPCTRL_ADDRCFG_STD                     0x00000001u        /**< Standard Address map active */
#define SCU_SWAPCTRL_ADDRCFG_ALT                     0x00000002u        /**< Alternate Address map active */

#define UCB_CONFIRMATION_OFFSET                      0x01F0u
#define UCB_CONFIRMATION_WRITE_LENGTH_IN_BYTE        0x0010u
#define UCB_CONFIRMATION_WRITE_LENGTH_IN_WORD        0x0004u
#define UCB_CONFIRMATION_READ_LENGTH_IN_BYTE         0x0004u
#define UCB_CONFIRMATION_READ_LENGTH_IN_WORD         0x0001u

/* Ucb state confirmation code. */
#define UCB_CONFIRMATION_UNLOCKED_U32                0x43211234u
#define UCB_CONFIRMATION_UNLOCKED_U8                 0x34u, 0x12u, 0x21, 0x43u
#define UCB_CONFIRMATION_CONFIRMED_U32               0x57B5327Fu
#define UCB_CONFIRMATION_CONFIRMED_U8                0x7Fu, 0x32u, 0xB5u, 0x57u
#define UCB_CONFIRMATION_ERASED_U32                  0x00000000u
#define UCB_CONFIRMATION_ERASED_U8                   0x00, 0x00u, 0x00u, 0x00u


typedef enum
{
    UCB01_BMHD0_ORIG    = 0u,
    UCB08_BMHD0_COPY    = 8u,
    UCB18_DBG_ORIG      = 18u,
    UCB20_HSMCOTP0_ORIG = 20u,
    UCB23_SWAP_ORIG     = 23u,
    UCB26_DBG_COPY      = 26u,
    UCB28_HSMCOTP0_COPY = 28u,
    UCB31_SWAP_COPY     = 31u,
    UCB32_OTP0_ORIG     = 32u,
    UCB40_OTP0_COPY     = 40u,
    UCB_NONE            = 0xFFu
} EUM_UcbIndexType;

typedef enum
{
    UCB_CONFIRMATION_UNLOCKED  = 0x00u,
    UCB_CONFIRMATION_CONFIRMED = 0x01u,
    UCB_CONFIRMATION_ERASED    = 0x02u,
    UCB_CONFIRMATION_ERRORED   = 0x03u
} EUM_UcbConfirmationType;

typedef struct
{
    uint32 u32SwapAreaStartAddr;
    uint32 u32SwapAreaEndAddr;
    uint32 u32SwapAreaOffset;
} ST_SwapOffsetCfgType;

typedef struct
{
   uint32                      u32EntryCount;
   const ST_SwapOffsetCfgType* pstCfgEntry;
} ST_SwapDeviceCfgType;

typedef struct
{
   uint32                     u32DevIdMask;
   uint32                     u32DevIdValue;
   const ST_SwapDeviceCfgType *devCfg;
} ST_SwapDevLookUpTblType;

extern int verify_erased_range(uint32 verifyAddress, uint32 verifyLength);
extern int flash_read(uint32 readStartAddr, uint32 readLength, uint8 *pu8ReadBuffer);
extern int ucb_read(EUM_UcbIndexType enUcbIdx, uint32 readOffset, uint32 readLength, uint8 *pu8ReadBuffer);
extern int ucb_write(EUM_UcbIndexType enUcbIdx, uint32 writeOffset, uint32 writeLength, uint8 *WriterBuffer);
extern EUM_UcbConfirmationType ucb_read_confirmation(EUM_UcbIndexType enUcbIdx);
extern void write_dflash(uint32 addr, uint32 val_l, uint32 val_h);
extern void ucb_erase(EUM_UcbIndexType enUcbIdx);
extern int ucb_write_confirmation(EUM_UcbIndexType enUcbIdx, EUM_UcbConfirmationType enUcbConfirmState);
#endif /* UCB_FLASH_H_ */
